# Generated by Django 2.1.7 on 2020-02-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_field', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
